export const products = [
  {
    id: 1,
    image: "../assets/images/classic-yellow.png",
    name: "Classic Yellow Duck",
    price: 9.99,
    description:
      'The icon of childhood joy. reimagined for the modern collector. Our signature yellow duck features a perfectly weighted bottom for the ultimate floating experience. Hand-finished for that premium tactile "squish" that defines a DuckStore original.',
    stock: 42,
    category: "Classic",
    badge1Img: "../assets/icons/Unsincable.svg",
    badge1: "Unsinkable",
    badge1Class: "product-badges",
    badge2Img: "../assets/icons/Non-Toxic.svg",
    badge2: "Non-Toxic",
    badge2Class: "product-badges",
  },
  {
    id: 2,
    image: "../assets/images/captain-quack.png",
    name: "Captain Quack",
    price: 14.99,
    description:
      "Command the bathtub with authority. Captain Quack features hand-painted nautical stripes and a signature felt officer's cap for the serious collector. Expertly balanced to survive the roughest of soapy seas, this limited edition sailor is a testament to craftsmanship and maritime charm.",
    stock: 12,
    category: "Limited edition",
    badge1Img: "../assets/icons/sea.png",
    badge1: "Sea Ready",
    badge1Class: "product-badges",
    badge2Img: "../assets/icons/handpainted.png",
    badge2: "Hand Painted",
    badge2Class: "product-badges",
  },
  {
    id: 3,
    image: "../assets/images/astro-duck.png",
    name: "Astro-Duck",
    price: 16.99,
    description:
      "One small splash for a duck, one giant leap for duck-kind. The Astro Duck is engineered for deep-space exploration and high-altitude relaxation. Featuring a stunning chrome-finished helmet with a constellation visor reflection and a specialized zero-gravity weight balance, this cosmic traveler is designed to stay upright in any orbit.",
    stock: 15,
    category: "Limited edition",
    badge1Img: "../assets/icons/antigravity.svg",
    badge1: "Zero Gravity",
    badge1Class: "product-badges",
    badge2Img: "../assets/icons/chrome-finish.svg",
    badge2: "Chrome Finish",
    badge2Class: "product-badges",
  },
  {
    id: 4,
    image: "../assets/images/chef-quack.png",
    name: "Chef Quack",
    price: 11.99,
    description:
      "The secret ingredient to a perfect kitchen. Chef Quack comes fully prepared to whip up some fun with his professional-grade miniature toque and stainless steel whisk. Featuring a classic red-checkered neckerchief, this culinary master is the ultimate gift for foodies and home cooks alike.",
    stock: 56,
    category: "Limited edition",
    badge1Img: "../assets/icons/kitchen-svg",
    badge1: "Kitchen Safe",
    badge1Class: "product-badges",
    badge2Img: "../assets/icons/kitchen-safe.svg",
    badge2: "Hand Stitched",
    badge2Class: "product-badges",
  },
  {
    id: 5,
    image: "../assets/images/superhero-duck-on-building.png",
    name: "Superhero Duck",
    price: 12.99,
    description:
      'Not all heroes wear bubbles—some wear capes. Superhero Duck is here to defend your bathroom from the forces of boredom. Featuring a custom-stitched midnight blue fabric cape, a signature "D" chest emblem, and a sleek heroic mask, this duck is engineered in a dynamic "power pose" to inspire bravery in every splash.',
    stock: 89,
    category: "Exclusive",
    badge1Img: "../assets/icons/action-pose.svg",
    badge1: "Action Pose",
    badge1Class: "product-badges",
    badge2Img: "../assets/icons/ultra-durable.svg",
    badge2: "Ultra Durable",
    badge2Class: "product-badges",
  },
  {
    id: 6,
    image: "../assets/images/zen-master.png",
    name: "Zen Master",
    price: 13.99,
    description:
      "Find your center amidst the bubbles. The Zen Master Duck is more than a companion; it's a sensory experience. Crafted from premium soft-touch silicone and infused with a calming lavender scent, this duck features sculpted mala beads and a meditative pose designed to bring absolute serenity to your self-care ritual.",
    stock: 24,
    category: "Exclusive",
    badge1Img: "../assets/icons/lavander-scent.svg",
    badge1: "Lavender Scent",
    badge1Class: "product-badges",
    badge2Img: "../assets/icons/soft-touch.svg",
    badge2: "Soft Touch",
    badge2Class: "product-badges",
  },
];
